[database]
url = "sqlite:wl-dev.sqlite"
min_connections = 1
max_connections = 5
connect_timeout = 2
idle_timeout = 60

[app]
token_secret = "0000000000000000000000000000000000000000000000000000000000000000"

[esi]
client_id = "EVE Client ID"
client_secret = "EVE Client Secret"
url = "https://waitlist.mycooldomain.local/auth/cb"

[sse]
url = "https://waitlist.mycooldomain.local
secret = "0000000000000000000000000000000000000000000000000000000000000000"

[fleet_updater]
enable = true
min_in_fleet = 8

[skill_updater]
enable = true
runtime = 86400
